# Etapa 1: imagem base
FROM node:18-alpine

# Etapa 2: criar diretório de trabalho no container
WORKDIR /app

# Etapa 3: copiar dependências e instalar
COPY package*.json ./
RUN npm install

# Etapa 4: copiar o restante do código
COPY . .

# Etapa 5: expor a porta usada no app
EXPOSE 3000

# Etapa 6: iniciar o app
CMD ["npm", "start"]
