# Etapa 1: imagem base
FROM node:18-alpine

# Etapa 2: diretório de trabalho no container
WORKDIR /app

# Etapa 3: copiar dependências
COPY package*.json ./

# Etapa 4: instalar dependências
RUN npm install

# Etapa 5: copiar o restante do projeto
COPY . .

# Etapa 6: expor a porta usada pela aplicação
EXPOSE 3000

# Etapa 7: comando de start
CMD ["npm", "start"]
